### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by XLF-xlf** [fjhzhixi/3D-SPS#8]
When I run "python setup.py install",it failed.How can I solve it?
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/4] /usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/                                    lib/python3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torc                                    h/csrc/api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/                                    sps_env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/incl                                    ude/python3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/sampling_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet2/                                    build/temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS                                    __ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-al                                    l -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=s                                    m_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_37 -g                                    encode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=                                    compute_62,code=sm_62 -std=c++14
FAILED: /home1/xlfHD/3D-SPS/lib/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o
/usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/lib/py                                    thon3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torch/csrc                                    /api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/sps_en                                    v/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/include/py                                    thon3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/sampling_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet2/build/                                    temp.linux-x86_64-cpython-38/_ext_src/src/sampling_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D_                                    _CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-all -DTO                                    RCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -                                    gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_37 -gencode                                    =arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=comput                                    e_62,code=sm_62 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
[2/4] /usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/                                    lib/python3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torc                                    h/csrc/api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/                                    sps_env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/incl                                    ude/python3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/ball_query_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet                                    2/build/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERS                                    IONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compres                                    s-all -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,co                                    de=sm_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_3                                    7 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=a                                    rch=compute_62,code=sm_62 -std=c++14
FAILED: /home1/xlfHD/3D-SPS/lib/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o
/usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/lib/py                                    thon3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torch/csrc                                    /api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/sps_en                                    v/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/include/py                                    thon3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/ball_query_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet2/buil                                    d/temp.linux-x86_64-cpython-38/_ext_src/src/ball_query_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__                                     -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-all                                     -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_                                    61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_37 -gen                                    code=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=co                                    mpute_62,code=sm_62 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
[3/4] /usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/                                    lib/python3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torc                                    h/csrc/api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/                                    sps_env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/incl                                    ude/python3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/interpolate_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointne                                    t2/build/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVE                                    RSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compr                                    ess-all -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,                                    code=sm_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute                                    _37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode                                    =arch=compute_62,code=sm_62 -std=c++14
FAILED: /home1/xlfHD/3D-SPS/lib/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o
/usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/lib/py                                    thon3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torch/csrc                                    /api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/sps_en                                    v/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/include/py                                    thon3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/interpolate_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet2/bui                                    ld/temp.linux-x86_64-cpython-38/_ext_src/src/interpolate_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS                                    __ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-al                                    l -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=s                                    m_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_37 -g                                    encode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=                                    compute_62,code=sm_62 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
[4/4] /usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/                                    lib/python3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torc                                    h/csrc/api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/                                    sps_env/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/incl                                    ude/python3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/group_points_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointn                                    et2/build/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CON                                    VERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -com                                    press-all -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_6                                    1,code=sm_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compu                                    te_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -genco                                    de=arch=compute_62,code=sm_62 -std=c++14
FAILED: /home1/xlfHD/3D-SPS/lib/pointnet2/build/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o
/usr/local/cuda-9.0/bin/nvcc -I/home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/include -I/home/xlf/.conda/envs/sps_env/lib/py                                    thon3.8/site-packages/torch/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/torch/csrc                                    /api/include -I/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/include/TH -I/home/xlf/.conda/envs/sps_en                                    v/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda-9.0/include -I/home/xlf/.conda/envs/sps_env/include/py                                    thon3.8 -c -c /home1/xlfHD/3D-SPS/lib/pointnet2/_ext_src/src/group_points_gpu.cu -o /home1/xlfHD/3D-SPS/lib/pointnet2/bu                                    ild/temp.linux-x86_64-cpython-38/_ext_src/src/group_points_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIO                                    NS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -Xfatbin -compress-                                    all -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code                                    =sm_61 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_37,code=compute_37                                     -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arc                                    h=compute_62,code=sm_62 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_75'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1509, in _run_ninj                                    a_build
    subprocess.run(
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    setup(
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_comma                                    nds
    dist.run_commands()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_comma                                    nds
    self.run_command(cmd)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_comma                                    nd
    cmd_obj.run()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_in                                    stall
    self.run_command('bdist_egg')
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_comman                                    d
    self.distribution.run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_comma                                    nd
    cmd_obj.run()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_co                                    mmand
    self.run_command(cmdname)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_comman                                    d
    self.distribution.run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_comma                                    nd
    cmd_obj.run()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 11                                    2, in build
    self.run_command('build_ext')
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_comman                                    d
    self.distribution.run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_comma                                    nd
    cmd_obj.run()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346,                                     in run
    self.build_extensions()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 649, in build_exte                                    nsions
    build_ext.build_extensions(self)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 466,                                     in build_extensions
    self._build_extensions_serial()
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 492,                                     in _build_extensions_serial
    self.build_extension(ext)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_e                                    xtension
    _build_ext.build_extension(self, ext)
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 547,                                     in build_extension
    objects = self.compiler.compile(
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 469, in unix_wrap_                                    ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1228, in _write_ni                                    nja_file_and_compile_objects
    _run_ninja_build(
  File "/home/xlf/.conda/envs/sps_env/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninj                                    a_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by fjhzhixi** [comment]
This error is caused by pointnet++ install, you are likely to find relevant solutions to this error in the following link:
[https://github.com/erikwijmans/Pointnet2_PyTorch/issues](url)
